# Site
title: "SHIRASAGI 開発マニュアル"
author: "SHIRASAGI Project"

# Conversion
#markdown: kramdown
markdown: redcarpet
exclude: ["vendor", "Gemfile", "Gemfile.lock"]
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
